version: "3.9"
services:
  nats1:
    image: docker.io/nats:2.9.20
    networks:
      - nats-network # 네트워크 추가
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats1:/data
    restart: unless-stopped
    command:
      - "--name=nats1"
      - "--cluster_name=c1"
      - "--cluster=nats://0.0.0.0:6222" # 바인딩 주소 수정
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  nats2:
    image: docker.io/nats:2.9.20
    networks:
      - nats-network # 네트워크 추가
    ports:
      - "4223:4222"
      - "8223:8222"
    volumes:
      - nats2:/data
    restart: unless-stopped
    command:
      - "--name=nats2"
      - "--cluster_name=c1"
      - "--cluster=nats://0.0.0.0:6222" # 바인딩 주소 수정
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  nats3:
    image: docker.io/nats:2.9.20
    networks:
      - nats-network # 네트워크 추가
    ports:
      - "4224:4222"
      - "8224:8222"
    volumes:
      - nats3:/data
    restart: unless-stopped
    command:
      - "--name=nats3"
      - "--cluster_name=c1"
      - "--cluster=nats://0.0.0.0:6222" # 바인딩 주소 수정
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

# 네트워크 정의 추가
networks:
  nats-network:
    driver: bridge

volumes:
  nats1:
    external: true
  nats2:
    external: true
  nats3:
    external: true
