version: "3.8"

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu_container
    volumes:
      - ./app:/app
    tty: true
    environment:
      - CURL_SSL_NO_VERIFY=true
