version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 13306:3306
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    platform: linux/x86_64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
volumes:
  mysql-data:
